################################# Default configuration ###################
# provide your domain here
baseURL = "https://nunchuk.io"
# theme
theme = "dot-hugo"
# site title
title = "Nunchuk"
# disable language
disableLanguages = ["fr"]
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = "images/Horizontal-Logo-2.1.png"
# logo white is for homepage logo, you can use colorful logo too...
logo_white = "images/Horizontal-Logo-2.png"
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
description = "Nunchuk – The safest and most advanced self-custody solution for your bitcoin"
author = "hugo"
image = "images/Horizontal-Logo-2.png" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#031f2b"
body_color = "#f9f9f9"
text_color = "#031f2b"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "https://contact-form.nunchuk.io/contact"
contact_form_success = "Thank you for contacting us.\nWe will get back in touch soon!"

############################## social links ##############################
#[[params.social]]
#icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
#name = "Facebook"
#link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
name = "Twitter"
link = "https://twitter.com/nunchuk_io"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
name = "Github"
link = "https://github.com/nunchuk-io"


[[params.social]]
icon = "ti-headphone-alt" # themify icon pack : https://themify.me/themify-icons
name = "Slack"
link = "https://join.slack.com/t/nunchukio/shared_invite/zt-xqdlvl5g-xKKohQu_R7IUo7_np8rVaw"
  
#[[params.social]]
#icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
#name = "Linkedin"
#link = "#"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "©2021 Nunchuk. All rights reserved."

# banner
[Languages.en.params.banner]
title = "Support Center & Knowledge Base"
subtitle = "Find answers from our team quickly or get in touch"
bg_image = ""
placeholder = "Enter your search keywords here"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = ""
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact/"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Home"
url = "https://nunchuk.io"
weight = 1
  [Languages.en.menu.main.params]
    hrefTargetBlank = true

[[Languages.en.menu.main]]
name = "Faq"
url = "faq/"
weight = 2

[[Languages.en.menu.main]]
name = "Contact"
url = "contact/"
weight = 3
